"""CLI entrypoint for DocGen."""

from __future__ import annotations

from pathlib import Path
from typing import Optional

import typer

try:
    from rich.console import Console
    from rich.table import Table

    _RICH_AVAILABLE = True
except ImportError:  # pragma: no cover - optional UX
    _RICH_AVAILABLE = False

from .config import DocGenConfig, default_config, load_config, resolve_config_path, write_config
from .errors import ConfigError, DocGenError, ExitCode, UsageError
from .logging import get_logger, setup_logging
from .services.build_service import build_docs
from .services.scan_service import scan_repo
from .utils.paths import resolve_repo_path

app = typer.Typer(add_completion=False, no_args_is_help=True)
_DEBUG = False


@app.callback()
def main(
    verbose: bool = typer.Option(False, "--verbose", "-v", help="Enable debug logging"),
    debug: bool = typer.Option(False, "--debug", help="Show stack traces on error"),
) -> None:
    global _DEBUG
    _DEBUG = debug
    setup_logging(verbose or debug)


def _handle_error(exc: Exception) -> None:
    logger = get_logger()
    if _DEBUG:
        if isinstance(exc, DocGenError):
            logger.exception("Error", exc_info=exc)
            raise typer.Exit(code=exc.exit_code)
        logger.exception("Unexpected error", exc_info=exc)
        raise typer.Exit(code=ExitCode.UNEXPECTED)
    if isinstance(exc, DocGenError):
        logger.error(str(exc))
        raise typer.Exit(code=exc.exit_code)
    logger.error("Unexpected error: %s", exc)
    raise typer.Exit(code=ExitCode.UNEXPECTED)


def _readme_template(project_name: str) -> str:
    return (
        f"# {project_name}\n\n"
        "## Summary\n"
        "<!-- DOCGEN:BEGIN id=\"readme.summary\" -->\n"
        "> Generated by DocGen. Do not edit this block manually.\n\n"
        "TBD\n"
        "<!-- DOCGEN:END id=\"readme.summary\" -->\n\n"
        "## Stack\n"
        "<!-- DOCGEN:BEGIN id=\"readme.stack\" -->\n"
        "> Generated by DocGen. Do not edit this block manually.\n\n"
        "TBD\n"
        "<!-- DOCGEN:END id=\"readme.stack\" -->\n\n"
        "## Commands\n"
        "<!-- DOCGEN:BEGIN id=\"readme.commands\" -->\n"
        "> Generated by DocGen. Do not edit this block manually.\n\n"
        "TBD\n"
        "<!-- DOCGEN:END id=\"readme.commands\" -->\n\n"
        "## Documentation\n"
        "<!-- DOCGEN:BEGIN id=\"readme.documentation\" -->\n"
        "> Generated by DocGen. Do not edit this block manually.\n\n"
        "TBD\n"
        "<!-- DOCGEN:END id=\"readme.documentation\" -->\n\n"
        "## Notes manuelles\n"
        "Add any manual notes here.\n"
    )


def _architecture_template() -> str:
    return (
        "# Architecture\n\n"
        "## Overview\n"
        "<!-- DOCGEN:BEGIN id=\"arch.overview\" -->\n"
        "> Generated by DocGen. Do not edit this block manually.\n\n"
        "TBD\n"
        "<!-- DOCGEN:END id=\"arch.overview\" -->\n\n"
        "## Components\n"
        "<!-- DOCGEN:BEGIN id=\"arch.components\" -->\n"
        "> Generated by DocGen. Do not edit this block manually.\n\n"
        "TBD\n"
        "<!-- DOCGEN:END id=\"arch.components\" -->\n\n"
        "## Data flow\n"
        "<!-- DOCGEN:BEGIN id=\"arch.data_flow\" -->\n"
        "> Generated by DocGen. Do not edit this block manually.\n\n"
        "TBD\n"
        "<!-- DOCGEN:END id=\"arch.data_flow\" -->\n\n"
        "## Deployment\n"
        "<!-- DOCGEN:BEGIN id=\"arch.deployment\" -->\n"
        "> Generated by DocGen. Do not edit this block manually.\n\n"
        "TBD\n"
        "<!-- DOCGEN:END id=\"arch.deployment\" -->\n\n"
        "## Notes manuelles\n"
        "Add any manual notes here.\n"
    )


def _create_templates(output_dir: Path, project_name: str) -> list[Path]:
    created: list[Path] = []
    readme_path = output_dir / "README.md"
    arch_path = output_dir / "ARCHITECTURE.md"

    if not readme_path.exists():
        readme_path.write_text(_readme_template(project_name), encoding="utf-8")
        created.append(readme_path)

    if not arch_path.exists():
        arch_path.write_text(_architecture_template(), encoding="utf-8")
        created.append(arch_path)

    return created


def _resolve_config(repo_path: Path, config_path: Optional[Path]) -> DocGenConfig:
    require_exists = config_path is not None
    return load_config(repo_path, config_path, require_exists=require_exists)


@app.command()
def init(
    repo: Optional[Path] = typer.Option(None, "--repo", "-r", help="Repository path"),
    config: Optional[Path] = typer.Option(None, "--config", "-c", help="Config file path"),
) -> None:
    """Initialize docgen.yaml and create output directory."""
    try:
        repo_path = resolve_repo_path(repo)
        config_path = resolve_config_path(repo_path, config)
        config_data = default_config()
        write_config(config_path, config_data, overwrite=False)

        output_dir = (repo_path / config_data.output_dir).resolve()
        output_dir.mkdir(parents=True, exist_ok=True)
        created_docs = _create_templates(output_dir, repo_path.name)

        typer.echo(f"Config created: {config_path}")
        typer.echo(f"Output dir: {output_dir}")
        typer.echo(f"Exclude: {', '.join(config_data.exclude)}")
        if created_docs:
            for path in created_docs:
                typer.echo(f"Created: {path}")
        else:
            typer.echo("README.md and ARCHITECTURE.md already exist; skipped.")
    except Exception as exc:
        _handle_error(exc)


@app.command()
def scan(
    repo: Optional[Path] = typer.Option(None, "--repo", "-r", help="Repository path"),
    config: Optional[Path] = typer.Option(None, "--config", "-c", help="Config file path"),
    format: str = typer.Option("text", "--format", "-f", help="Output format: text|json"),
) -> None:
    """Scan repository and output ProjectInfo."""
    try:
        repo_path = resolve_repo_path(repo)
        config_data = _resolve_config(repo_path, config)

        fmt = format.lower().strip()
        if fmt not in {"text", "json"}:
            raise UsageError("--format must be 'text' or 'json'")

        project = scan_repo(repo_path, config_data)

        if fmt == "json":
            typer.echo(project.to_json())
            return

        def display(value: str | None) -> str:
            return value if value else "-"

        typer.echo(f"Project: {project.project_name}")
        typer.echo(f"Repo: {project.repo_root}")
        typer.echo(f"Output dir: {config_data.output_dir}")
        typer.echo(f"Exclude: {', '.join(config_data.exclude)}")

        if _RICH_AVAILABLE:
            console = Console()
            stack_table = Table(title="Stacks")
            stack_table.add_column("Name")
            stack_table.add_column("Confidence")
            stack_table.add_column("Evidence")
            if project.stacks:
                for stack in project.stacks:
                    stack_table.add_row(
                        stack.name,
                        f"{stack.confidence:.2f}",
                        ", ".join(stack.evidence) if stack.evidence else "-",
                    )
            else:
                stack_table.add_row("-", "-", "-")
            console.print(stack_table)

            cmd_table = Table(title="Commands")
            cmd_table.add_column("Type")
            cmd_table.add_column("Command")
            cmd_table.add_row("run", display(project.commands.run))
            cmd_table.add_row("test", display(project.commands.test))
            cmd_table.add_row("lint", display(project.commands.lint))
            cmd_table.add_row("build", display(project.commands.build))
            cmd_table.add_row("format", display(project.commands.format))
            console.print(cmd_table)
        else:
            typer.echo("Stacks:")
            if project.stacks:
                for stack in project.stacks:
                    evidence = ", ".join(stack.evidence) if stack.evidence else "-"
                    typer.echo(f"- {stack.name} (confidence {stack.confidence:.2f}): {evidence}")
            else:
                typer.echo("- none")

            typer.echo("Commands:")
            typer.echo(f"- run: {display(project.commands.run)}")
            typer.echo(f"- test: {display(project.commands.test)}")
            typer.echo(f"- lint: {display(project.commands.lint)}")
            typer.echo(f"- build: {display(project.commands.build)}")
            typer.echo(f"- format: {display(project.commands.format)}")

        typer.echo("Detected files:")
        if project.files_detected:
            for item in project.files_detected:
                typer.echo(f"- {item.path} ({item.type})")
        else:
            typer.echo("- none")
        typer.echo(f"CI: {', '.join(project.ci) if project.ci else '-'}")
        typer.echo(f"Package manager: {project.package_manager or '-'}")
        typer.echo(f"Python tooling: {project.python_tooling or '-'}")
        if project.warnings:
            typer.echo("Warnings:")
            for warning in project.warnings:
                typer.echo(f"- {warning}")
    except Exception as exc:
        _handle_error(exc)


@app.command()
def build(
    repo: Optional[Path] = typer.Option(None, "--repo", "-r", help="Repository path"),
    config: Optional[Path] = typer.Option(None, "--config", "-c", help="Config file path"),
    dry_run: bool = typer.Option(False, "--dry-run", help="Do not write files"),
    force: bool = typer.Option(False, "--force", help="Overwrite existing files"),
    doxygen: bool = typer.Option(False, "--doxygen", help="Run Doxygen if Doxyfile exists"),
) -> None:
    """Build documentation."""
    try:
        repo_path = resolve_repo_path(repo)
        config_data = _resolve_config(repo_path, config)

        plan = build_docs(repo_path, config_data, dry_run=dry_run, force=force, doxygen=doxygen)

        if dry_run:
            typer.echo("Dry run. Files that would be generated:")
        else:
            typer.echo("Files prepared:")

        for path in plan.targets:
            try:
                rel = path.relative_to(repo_path)
                typer.echo(f"- {rel}")
            except ValueError:
                typer.echo(f"- {path}")
        typer.echo("Sections:")
        for target in plan.targets:
            report = plan.reports.get(target)
            if not report:
                continue
            label = target.name
            typer.echo(f"- {label}:")
            if report.created:
                typer.echo("  - created")
            if report.overwritten:
                typer.echo("  - overwritten")
            if report.added:
                typer.echo(f"  - added: {', '.join(report.added)}")
            if report.replaced:
                typer.echo(f"  - replaced: {', '.join(report.replaced)}")
            if report.unchanged:
                typer.echo(f"  - unchanged: {', '.join(report.unchanged)}")
        if doxygen:
            if plan.doxygen_would_run and plan.doxygen_file:
                typer.echo(f"Doxygen: would run using {plan.doxygen_file}")
            elif plan.doxygen_ran and plan.doxygen_file:
                typer.echo(f"Doxygen: ran using {plan.doxygen_file}")
    except Exception as exc:
        _handle_error(exc)
